version: “3”
services:
 nodejs:
   container_name: budokan-nodejs
   image: node:10-alpine
   volumes:
     - .:/home/data/node/budokan/
   working_dir: /home/data/node/budokan/
   environment:
     - HOST=0.0.0.0
     - NODE_ENV=production
     - NODE_CONFIG_ENV=sony-sp-int
     - REDIS_HOST=budokan-redis
     - REDIS_PORT=6379
     - https_server=true
     - cache_enabled=true
   networks:
     local:
       aliases:
         - nodejs
   expose: [‘3000’]
   command:
     [‘node’, ‘src/server’]
 redis:
   container_name: budokan-redis
   image: “redis:alpine”
   restart: unless-stopped
   expose: [‘6379’]
   networks:
     - local
   volumes:
     - ./extras/redis/redis.conf:/usr/local/etc/redis/redis.conf
   command:
     [‘redis-server’, ‘/usr/local/etc/redis/redis.conf’]
 nginx:
   container_name: budokan-nginx
   image: nginx:alpine
   restart: unless-stopped
   ports:
     - “8080:80”
     - “8443:443"
   networks:
     - local
   volumes:
     - ./extras/local-dev/ssl:/etc/certs/localhost
     - ./extras/.local/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
     - ./src/:/home/data/node/budokan/:ro
networks:
 local: